# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import permission_pb2 as permission__pb2


class PermissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPolicies = channel.unary_unary(
                '/permission.Permission/GetPolicies',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=permission__pb2.GetPoliciesReply.FromString,
                )
        self.GetPoliciesByUser = channel.unary_unary(
                '/permission.Permission/GetPoliciesByUser',
                request_serializer=permission__pb2.GetPoliciesByUserRequest.SerializeToString,
                response_deserializer=permission__pb2.GetPoliciesByUserReply.FromString,
                )
        self.CreatePolicy = channel.unary_unary(
                '/permission.Permission/CreatePolicy',
                request_serializer=permission__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=permission__pb2.CreatePolicyReply.FromString,
                )
        self.CheckPolicy = channel.unary_unary(
                '/permission.Permission/CheckPolicy',
                request_serializer=permission__pb2.CheckPolicyRequest.SerializeToString,
                response_deserializer=permission__pb2.CheckPolicyReply.FromString,
                )


class PermissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoliciesByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicies,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=permission__pb2.GetPoliciesReply.SerializeToString,
            ),
            'GetPoliciesByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoliciesByUser,
                    request_deserializer=permission__pb2.GetPoliciesByUserRequest.FromString,
                    response_serializer=permission__pb2.GetPoliciesByUserReply.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=permission__pb2.CreatePolicyRequest.FromString,
                    response_serializer=permission__pb2.CreatePolicyReply.SerializeToString,
            ),
            'CheckPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPolicy,
                    request_deserializer=permission__pb2.CheckPolicyRequest.FromString,
                    response_serializer=permission__pb2.CheckPolicyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permission.Permission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Permission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/GetPolicies',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            permission__pb2.GetPoliciesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPoliciesByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/GetPoliciesByUser',
            permission__pb2.GetPoliciesByUserRequest.SerializeToString,
            permission__pb2.GetPoliciesByUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/CreatePolicy',
            permission__pb2.CreatePolicyRequest.SerializeToString,
            permission__pb2.CreatePolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/CheckPolicy',
            permission__pb2.CheckPolicyRequest.SerializeToString,
            permission__pb2.CheckPolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
