# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10permission.proto\x12\npermission\"#\n\x10GetPolicyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"0\n\x0eGetPolicyReply\x12\x0e\n\x06object\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"Q\n\x10GetPoliciesReply\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12,\n\x08policies\x18\x02 \x03(\x0b\x32\x1a.permission.GetPolicyReply\"F\n\x13\x43reatePolicyRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\"D\n\x11\x43reatePolicyReply\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t2\xa7\x01\n\nPermission\x12I\n\x0bGetPolicies\x12\x1c.permission.GetPolicyRequest\x1a\x1c.permission.GetPoliciesReply\x12N\n\x0c\x43reatePolicy\x12\x1f.permission.CreatePolicyRequest\x1a\x1d.permission.CreatePolicyReplyb\x06proto3')



_GETPOLICYREQUEST = DESCRIPTOR.message_types_by_name['GetPolicyRequest']
_GETPOLICYREPLY = DESCRIPTOR.message_types_by_name['GetPolicyReply']
_GETPOLICIESREPLY = DESCRIPTOR.message_types_by_name['GetPoliciesReply']
_CREATEPOLICYREQUEST = DESCRIPTOR.message_types_by_name['CreatePolicyRequest']
_CREATEPOLICYREPLY = DESCRIPTOR.message_types_by_name['CreatePolicyReply']
GetPolicyRequest = _reflection.GeneratedProtocolMessageType('GetPolicyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOLICYREQUEST,
  '__module__' : 'permission_pb2'
  # @@protoc_insertion_point(class_scope:permission.GetPolicyRequest)
  })
_sym_db.RegisterMessage(GetPolicyRequest)

GetPolicyReply = _reflection.GeneratedProtocolMessageType('GetPolicyReply', (_message.Message,), {
  'DESCRIPTOR' : _GETPOLICYREPLY,
  '__module__' : 'permission_pb2'
  # @@protoc_insertion_point(class_scope:permission.GetPolicyReply)
  })
_sym_db.RegisterMessage(GetPolicyReply)

GetPoliciesReply = _reflection.GeneratedProtocolMessageType('GetPoliciesReply', (_message.Message,), {
  'DESCRIPTOR' : _GETPOLICIESREPLY,
  '__module__' : 'permission_pb2'
  # @@protoc_insertion_point(class_scope:permission.GetPoliciesReply)
  })
_sym_db.RegisterMessage(GetPoliciesReply)

CreatePolicyRequest = _reflection.GeneratedProtocolMessageType('CreatePolicyRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOLICYREQUEST,
  '__module__' : 'permission_pb2'
  # @@protoc_insertion_point(class_scope:permission.CreatePolicyRequest)
  })
_sym_db.RegisterMessage(CreatePolicyRequest)

CreatePolicyReply = _reflection.GeneratedProtocolMessageType('CreatePolicyReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOLICYREPLY,
  '__module__' : 'permission_pb2'
  # @@protoc_insertion_point(class_scope:permission.CreatePolicyReply)
  })
_sym_db.RegisterMessage(CreatePolicyReply)

_PERMISSION = DESCRIPTOR.services_by_name['Permission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPOLICYREQUEST._serialized_start=32
  _GETPOLICYREQUEST._serialized_end=67
  _GETPOLICYREPLY._serialized_start=69
  _GETPOLICYREPLY._serialized_end=117
  _GETPOLICIESREPLY._serialized_start=119
  _GETPOLICIESREPLY._serialized_end=200
  _CREATEPOLICYREQUEST._serialized_start=202
  _CREATEPOLICYREQUEST._serialized_end=272
  _CREATEPOLICYREPLY._serialized_start=274
  _CREATEPOLICYREPLY._serialized_end=342
  _PERMISSION._serialized_start=345
  _PERMISSION._serialized_end=512
# @@protoc_insertion_point(module_scope)
